# Generated by Django 4.2 on 2024-11-17 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_currencyrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('converted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conversion_date', models.DateTimeField(auto_now_add=True)),
                ('exchanged_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanged_conversions', to='exchange.currency')),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_conversions', to='exchange.currency')),
            ],
        ),
    ]
