# Generated by Django 4.2 on 2024-11-17 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_currencyconversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
    ]
